sudo: required
services:
  - docker

before_install:
  - docker build -t takayone615/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true takayone615/react-test npm test -- --coverage

after_success:
  - docker build -t takayone615/multi-client ./client
  - docker build -t takayone615/multi-nginx ./nginx
  - docker build -t takayone615/multi-server ./server
  - docker build -t takayone615/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push takayone615/multi-client
  - docker push takayone615/multi-nginx
  - docker push takayone615/multi-server
  - docker push takayone615/multi-worker
#
deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-northeast-1-499041746093
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
