sudo: required
services:
  - docker
before_install:
  - docker build -t takatakayone/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true takatakayone/react-test npm test -- --coverage

after_success:
  - docker build -t takatakayone/multi-client ./client
  - docker build -t takatakayone/multi-nginx ./nginx
  - docker build -t takatakayone/multi-server ./server
  - docker build -t takatakayone/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push takatakayone/multi-client
  - docker push takatakayone/multi-nginx
  - docker push takatakayone/multi-server
  - docker push takatakayone/multi-worker


#sudo: required
#services:
#  - docker
#
#before_install:
#  - docker build -t takatakayone/react-test -f ./client/Dockerfile.dev ./client
#
#script:
#  - docker run -e CI=true takatakayone/react-test npm test -- --coverage
#
#after_success:
#  - docker build -t takatakayone/multi-client ./client
#  - docker build -t takatakayone/multi-nginx ./nginx
#  - docker build -t takatakayone/multi-server ./server
#  - docker build -t takatakayone/multi-worker ./worker
#  # Log in to the docker CLI
#  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#  # Take those images and push them to docker hub
#  - docker push takatakayone/multi-client
#  - docker push takatakayone/multi-nginx
#  - docker push takatakayone/multi-server
#  - docker push takatakayone/multi-worker
#
#deploy:
#  provider: elasticbeanstalk
#  region: us-west-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-west-1-306476627547
#  bucket_path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
